POST http://localhost:8080/api/products
X-Api-Key: SECRET
Content-Type: application/json
Accept: application/json

{
  "id": "A0010",
  "name": "Macbook Pro 15",
  "price": 30000000,
  "quantity": 10
}

###

POST http://localhost:8080/api/products
Content-Type: application/json
Accept: application/json

{
  "id": "",
  "name": "",
  "price": 0,
  "quantity": -10
}

###

GET http://localhost:8080/api/products/A001
X-Api-Key: SECRET
Accept: application/json


###

GET http://localhost:8080/api/products/A0001
Accept: application/json


###

PUT http://localhost:8080/api/products/A001
Content-Type: application/json
Accept: application/json

{
  "name": "Apple Macbook Pro 15 2020",
  "price": 40000000,
  "quantity": 100
}

###

PUT http://localhost:8080/api/products/A002
Content-Type: application/json
Accept: application/json

{
  "name": "Apple Macbook Pro 15 2020",
  "price": 40000000,
  "quantity": 100
}

###

PUT http://localhost:8080/api/products/A001
Content-Type: application/json
Accept: application/json

{
  "name": "",
  "price": 0,
  "quantity": -100
}

###

DELETE http://localhost:8080/api/products/A001
Accept: application/json



###

GET http://localhost:8080/api/products
Accept: application/json

###

GET http://localhost:8080/api/products?size=5
Accept: application/json


###

GET http://localhost:8080/api/products?size=5&page=1
Accept: application/json